# https://github.com/google-github-actions/auth?tab=readme-ov-file#preferred-direct-workload-identity-federation
# https://docs.docker.com/build/ci/github-actions/share-image-jobs/
name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGION: us-east4
  # should correlate to artifact registry
  GAR_LOCATION: mhbuilder-ui

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - run: docker buildx build . -t ${{ env.GAR_LOCATION }} --output type=docker,dest=${{ runner.temp }}/image.tar